/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ResultadoOcr as PrismaResultadoOcr,
  ArchivoPdf as PrismaArchivoPdf,
} from "@prisma/client";

export class ResultadoOcrServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ResultadoOcrCountArgs, "select">
  ): Promise<number> {
    return this.prisma.resultadoOcr.count(args);
  }

  async resultadoOcrs(
    args: Prisma.ResultadoOcrFindManyArgs
  ): Promise<PrismaResultadoOcr[]> {
    return this.prisma.resultadoOcr.findMany(args);
  }
  async resultadoOcr(
    args: Prisma.ResultadoOcrFindUniqueArgs
  ): Promise<PrismaResultadoOcr | null> {
    return this.prisma.resultadoOcr.findUnique(args);
  }
  async createResultadoOcr(
    args: Prisma.ResultadoOcrCreateArgs
  ): Promise<PrismaResultadoOcr> {
    return this.prisma.resultadoOcr.create(args);
  }
  async updateResultadoOcr(
    args: Prisma.ResultadoOcrUpdateArgs
  ): Promise<PrismaResultadoOcr> {
    return this.prisma.resultadoOcr.update(args);
  }
  async deleteResultadoOcr(
    args: Prisma.ResultadoOcrDeleteArgs
  ): Promise<PrismaResultadoOcr> {
    return this.prisma.resultadoOcr.delete(args);
  }

  async getArchivoPdf(parentId: string): Promise<PrismaArchivoPdf | null> {
    return this.prisma.resultadoOcr
      .findUnique({
        where: { id: parentId },
      })
      .archivoPdf();
  }
}
