/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ResultadoOcrService } from "../resultadoOcr.service";
import { ResultadoOcrCreateInput } from "./ResultadoOcrCreateInput";
import { ResultadoOcr } from "./ResultadoOcr";
import { ResultadoOcrFindManyArgs } from "./ResultadoOcrFindManyArgs";
import { ResultadoOcrWhereUniqueInput } from "./ResultadoOcrWhereUniqueInput";
import { ResultadoOcrUpdateInput } from "./ResultadoOcrUpdateInput";

export class ResultadoOcrControllerBase {
  constructor(protected readonly service: ResultadoOcrService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ResultadoOcr })
  async createResultadoOcr(
    @common.Body() data: ResultadoOcrCreateInput
  ): Promise<ResultadoOcr> {
    return await this.service.createResultadoOcr({
      data: {
        ...data,

        archivoPdf: data.archivoPdf
          ? {
              connect: data.archivoPdf,
            }
          : undefined,
      },
      select: {
        archivoPdf: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        lenguajeDetectado: true,
        textoExtraido: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ResultadoOcr] })
  @ApiNestedQuery(ResultadoOcrFindManyArgs)
  async resultadoOcrs(@common.Req() request: Request): Promise<ResultadoOcr[]> {
    const args = plainToClass(ResultadoOcrFindManyArgs, request.query);
    return this.service.resultadoOcrs({
      ...args,
      select: {
        archivoPdf: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        lenguajeDetectado: true,
        textoExtraido: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ResultadoOcr })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async resultadoOcr(
    @common.Param() params: ResultadoOcrWhereUniqueInput
  ): Promise<ResultadoOcr | null> {
    const result = await this.service.resultadoOcr({
      where: params,
      select: {
        archivoPdf: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        lenguajeDetectado: true,
        textoExtraido: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ResultadoOcr })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateResultadoOcr(
    @common.Param() params: ResultadoOcrWhereUniqueInput,
    @common.Body() data: ResultadoOcrUpdateInput
  ): Promise<ResultadoOcr | null> {
    try {
      return await this.service.updateResultadoOcr({
        where: params,
        data: {
          ...data,

          archivoPdf: data.archivoPdf
            ? {
                connect: data.archivoPdf,
              }
            : undefined,
        },
        select: {
          archivoPdf: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          lenguajeDetectado: true,
          textoExtraido: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ResultadoOcr })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteResultadoOcr(
    @common.Param() params: ResultadoOcrWhereUniqueInput
  ): Promise<ResultadoOcr | null> {
    try {
      return await this.service.deleteResultadoOcr({
        where: params,
        select: {
          archivoPdf: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          lenguajeDetectado: true,
          textoExtraido: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
