/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ResultadoOcr } from "./ResultadoOcr";
import { ResultadoOcrCountArgs } from "./ResultadoOcrCountArgs";
import { ResultadoOcrFindManyArgs } from "./ResultadoOcrFindManyArgs";
import { ResultadoOcrFindUniqueArgs } from "./ResultadoOcrFindUniqueArgs";
import { CreateResultadoOcrArgs } from "./CreateResultadoOcrArgs";
import { UpdateResultadoOcrArgs } from "./UpdateResultadoOcrArgs";
import { DeleteResultadoOcrArgs } from "./DeleteResultadoOcrArgs";
import { ArchivoPdf } from "../../archivoPdf/base/ArchivoPdf";
import { ResultadoOcrService } from "../resultadoOcr.service";
@graphql.Resolver(() => ResultadoOcr)
export class ResultadoOcrResolverBase {
  constructor(protected readonly service: ResultadoOcrService) {}

  async _resultadoOcrsMeta(
    @graphql.Args() args: ResultadoOcrCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ResultadoOcr])
  async resultadoOcrs(
    @graphql.Args() args: ResultadoOcrFindManyArgs
  ): Promise<ResultadoOcr[]> {
    return this.service.resultadoOcrs(args);
  }

  @graphql.Query(() => ResultadoOcr, { nullable: true })
  async resultadoOcr(
    @graphql.Args() args: ResultadoOcrFindUniqueArgs
  ): Promise<ResultadoOcr | null> {
    const result = await this.service.resultadoOcr(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ResultadoOcr)
  async createResultadoOcr(
    @graphql.Args() args: CreateResultadoOcrArgs
  ): Promise<ResultadoOcr> {
    return await this.service.createResultadoOcr({
      ...args,
      data: {
        ...args.data,

        archivoPdf: args.data.archivoPdf
          ? {
              connect: args.data.archivoPdf,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => ResultadoOcr)
  async updateResultadoOcr(
    @graphql.Args() args: UpdateResultadoOcrArgs
  ): Promise<ResultadoOcr | null> {
    try {
      return await this.service.updateResultadoOcr({
        ...args,
        data: {
          ...args.data,

          archivoPdf: args.data.archivoPdf
            ? {
                connect: args.data.archivoPdf,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ResultadoOcr)
  async deleteResultadoOcr(
    @graphql.Args() args: DeleteResultadoOcrArgs
  ): Promise<ResultadoOcr | null> {
    try {
      return await this.service.deleteResultadoOcr(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => ArchivoPdf, {
    nullable: true,
    name: "archivoPdf",
  })
  async getArchivoPdf(
    @graphql.Parent() parent: ResultadoOcr
  ): Promise<ArchivoPdf | null> {
    const result = await this.service.getArchivoPdf(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
