/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Proceso } from "./Proceso";
import { ProcesoCountArgs } from "./ProcesoCountArgs";
import { ProcesoFindManyArgs } from "./ProcesoFindManyArgs";
import { ProcesoFindUniqueArgs } from "./ProcesoFindUniqueArgs";
import { CreateProcesoArgs } from "./CreateProcesoArgs";
import { UpdateProcesoArgs } from "./UpdateProcesoArgs";
import { DeleteProcesoArgs } from "./DeleteProcesoArgs";
import { ArchivoPdf } from "../../archivoPdf/base/ArchivoPdf";
import { ProcesoService } from "../proceso.service";
@graphql.Resolver(() => Proceso)
export class ProcesoResolverBase {
  constructor(protected readonly service: ProcesoService) {}

  async _procesosMeta(
    @graphql.Args() args: ProcesoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Proceso])
  async procesos(
    @graphql.Args() args: ProcesoFindManyArgs
  ): Promise<Proceso[]> {
    return this.service.procesos(args);
  }

  @graphql.Query(() => Proceso, { nullable: true })
  async proceso(
    @graphql.Args() args: ProcesoFindUniqueArgs
  ): Promise<Proceso | null> {
    const result = await this.service.proceso(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Proceso)
  async createProceso(
    @graphql.Args() args: CreateProcesoArgs
  ): Promise<Proceso> {
    return await this.service.createProceso({
      ...args,
      data: {
        ...args.data,

        archivoPdf: args.data.archivoPdf
          ? {
              connect: args.data.archivoPdf,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Proceso)
  async updateProceso(
    @graphql.Args() args: UpdateProcesoArgs
  ): Promise<Proceso | null> {
    try {
      return await this.service.updateProceso({
        ...args,
        data: {
          ...args.data,

          archivoPdf: args.data.archivoPdf
            ? {
                connect: args.data.archivoPdf,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Proceso)
  async deleteProceso(
    @graphql.Args() args: DeleteProcesoArgs
  ): Promise<Proceso | null> {
    try {
      return await this.service.deleteProceso(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => ArchivoPdf, {
    nullable: true,
    name: "archivoPdf",
  })
  async getArchivoPdf(
    @graphql.Parent() parent: Proceso
  ): Promise<ArchivoPdf | null> {
    const result = await this.service.getArchivoPdf(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
