/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProcesoService } from "../proceso.service";
import { ProcesoCreateInput } from "./ProcesoCreateInput";
import { Proceso } from "./Proceso";
import { ProcesoFindManyArgs } from "./ProcesoFindManyArgs";
import { ProcesoWhereUniqueInput } from "./ProcesoWhereUniqueInput";
import { ProcesoUpdateInput } from "./ProcesoUpdateInput";

export class ProcesoControllerBase {
  constructor(protected readonly service: ProcesoService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Proceso })
  async createProceso(
    @common.Body() data: ProcesoCreateInput
  ): Promise<Proceso> {
    return await this.service.createProceso({
      data: {
        ...data,

        archivoPdf: data.archivoPdf
          ? {
              connect: data.archivoPdf,
            }
          : undefined,
      },
      select: {
        archivoPdf: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        estado: true,
        id: true,
        mensajeError: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Proceso] })
  @ApiNestedQuery(ProcesoFindManyArgs)
  async procesos(@common.Req() request: Request): Promise<Proceso[]> {
    const args = plainToClass(ProcesoFindManyArgs, request.query);
    return this.service.procesos({
      ...args,
      select: {
        archivoPdf: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        estado: true,
        id: true,
        mensajeError: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Proceso })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async proceso(
    @common.Param() params: ProcesoWhereUniqueInput
  ): Promise<Proceso | null> {
    const result = await this.service.proceso({
      where: params,
      select: {
        archivoPdf: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        estado: true,
        id: true,
        mensajeError: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Proceso })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProceso(
    @common.Param() params: ProcesoWhereUniqueInput,
    @common.Body() data: ProcesoUpdateInput
  ): Promise<Proceso | null> {
    try {
      return await this.service.updateProceso({
        where: params,
        data: {
          ...data,

          archivoPdf: data.archivoPdf
            ? {
                connect: data.archivoPdf,
              }
            : undefined,
        },
        select: {
          archivoPdf: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          estado: true,
          id: true,
          mensajeError: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Proceso })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProceso(
    @common.Param() params: ProcesoWhereUniqueInput
  ): Promise<Proceso | null> {
    try {
      return await this.service.deleteProceso({
        where: params,
        select: {
          archivoPdf: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          estado: true,
          id: true,
          mensajeError: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
