/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Proceso as PrismaProceso,
  ArchivoPdf as PrismaArchivoPdf,
} from "@prisma/client";

export class ProcesoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ProcesoCountArgs, "select">): Promise<number> {
    return this.prisma.proceso.count(args);
  }

  async procesos(args: Prisma.ProcesoFindManyArgs): Promise<PrismaProceso[]> {
    return this.prisma.proceso.findMany(args);
  }
  async proceso(
    args: Prisma.ProcesoFindUniqueArgs
  ): Promise<PrismaProceso | null> {
    return this.prisma.proceso.findUnique(args);
  }
  async createProceso(args: Prisma.ProcesoCreateArgs): Promise<PrismaProceso> {
    return this.prisma.proceso.create(args);
  }
  async updateProceso(args: Prisma.ProcesoUpdateArgs): Promise<PrismaProceso> {
    return this.prisma.proceso.update(args);
  }
  async deleteProceso(args: Prisma.ProcesoDeleteArgs): Promise<PrismaProceso> {
    return this.prisma.proceso.delete(args);
  }

  async getArchivoPdf(parentId: string): Promise<PrismaArchivoPdf | null> {
    return this.prisma.proceso
      .findUnique({
        where: { id: parentId },
      })
      .archivoPdf();
  }
}
