/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ArchivoPdf } from "./ArchivoPdf";
import { ArchivoPdfCountArgs } from "./ArchivoPdfCountArgs";
import { ArchivoPdfFindManyArgs } from "./ArchivoPdfFindManyArgs";
import { ArchivoPdfFindUniqueArgs } from "./ArchivoPdfFindUniqueArgs";
import { CreateArchivoPdfArgs } from "./CreateArchivoPdfArgs";
import { UpdateArchivoPdfArgs } from "./UpdateArchivoPdfArgs";
import { DeleteArchivoPdfArgs } from "./DeleteArchivoPdfArgs";
import { ProcesoFindManyArgs } from "../../proceso/base/ProcesoFindManyArgs";
import { Proceso } from "../../proceso/base/Proceso";
import { ResultadoOcrFindManyArgs } from "../../resultadoOcr/base/ResultadoOcrFindManyArgs";
import { ResultadoOcr } from "../../resultadoOcr/base/ResultadoOcr";
import { TablaExtraidaFindManyArgs } from "../../tablaExtraida/base/TablaExtraidaFindManyArgs";
import { TablaExtraida } from "../../tablaExtraida/base/TablaExtraida";
import { ArchivoPdfService } from "../archivoPdf.service";
@graphql.Resolver(() => ArchivoPdf)
export class ArchivoPdfResolverBase {
  constructor(protected readonly service: ArchivoPdfService) {}

  async _archivoPdfsMeta(
    @graphql.Args() args: ArchivoPdfCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ArchivoPdf])
  async archivoPdfs(
    @graphql.Args() args: ArchivoPdfFindManyArgs
  ): Promise<ArchivoPdf[]> {
    return this.service.archivoPdfs(args);
  }

  @graphql.Query(() => ArchivoPdf, { nullable: true })
  async archivoPdf(
    @graphql.Args() args: ArchivoPdfFindUniqueArgs
  ): Promise<ArchivoPdf | null> {
    const result = await this.service.archivoPdf(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ArchivoPdf)
  async createArchivoPdf(
    @graphql.Args() args: CreateArchivoPdfArgs
  ): Promise<ArchivoPdf> {
    return await this.service.createArchivoPdf({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ArchivoPdf)
  async updateArchivoPdf(
    @graphql.Args() args: UpdateArchivoPdfArgs
  ): Promise<ArchivoPdf | null> {
    try {
      return await this.service.updateArchivoPdf({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ArchivoPdf)
  async deleteArchivoPdf(
    @graphql.Args() args: DeleteArchivoPdfArgs
  ): Promise<ArchivoPdf | null> {
    try {
      return await this.service.deleteArchivoPdf(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Proceso], { name: "procesos" })
  async findProcesos(
    @graphql.Parent() parent: ArchivoPdf,
    @graphql.Args() args: ProcesoFindManyArgs
  ): Promise<Proceso[]> {
    const results = await this.service.findProcesos(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [ResultadoOcr], { name: "resultadoOcrs" })
  async findResultadoOcrs(
    @graphql.Parent() parent: ArchivoPdf,
    @graphql.Args() args: ResultadoOcrFindManyArgs
  ): Promise<ResultadoOcr[]> {
    const results = await this.service.findResultadoOcrs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [TablaExtraida], { name: "tablaExtraidas" })
  async findTablaExtraidas(
    @graphql.Parent() parent: ArchivoPdf,
    @graphql.Args() args: TablaExtraidaFindManyArgs
  ): Promise<TablaExtraida[]> {
    const results = await this.service.findTablaExtraidas(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
