/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ArchivoPdf as PrismaArchivoPdf,
  Proceso as PrismaProceso,
  ResultadoOcr as PrismaResultadoOcr,
  TablaExtraida as PrismaTablaExtraida,
} from "@prisma/client";

export class ArchivoPdfServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ArchivoPdfCountArgs, "select">
  ): Promise<number> {
    return this.prisma.archivoPdf.count(args);
  }

  async archivoPdfs(
    args: Prisma.ArchivoPdfFindManyArgs
  ): Promise<PrismaArchivoPdf[]> {
    return this.prisma.archivoPdf.findMany(args);
  }
  async archivoPdf(
    args: Prisma.ArchivoPdfFindUniqueArgs
  ): Promise<PrismaArchivoPdf | null> {
    return this.prisma.archivoPdf.findUnique(args);
  }
  async createArchivoPdf(
    args: Prisma.ArchivoPdfCreateArgs
  ): Promise<PrismaArchivoPdf> {
    return this.prisma.archivoPdf.create(args);
  }
  async updateArchivoPdf(
    args: Prisma.ArchivoPdfUpdateArgs
  ): Promise<PrismaArchivoPdf> {
    return this.prisma.archivoPdf.update(args);
  }
  async deleteArchivoPdf(
    args: Prisma.ArchivoPdfDeleteArgs
  ): Promise<PrismaArchivoPdf> {
    return this.prisma.archivoPdf.delete(args);
  }

  async findProcesos(
    parentId: string,
    args: Prisma.ProcesoFindManyArgs
  ): Promise<PrismaProceso[]> {
    return this.prisma.archivoPdf
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .procesos(args);
  }

  async findResultadoOcrs(
    parentId: string,
    args: Prisma.ResultadoOcrFindManyArgs
  ): Promise<PrismaResultadoOcr[]> {
    return this.prisma.archivoPdf
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .resultadoOcrs(args);
  }

  async findTablaExtraidas(
    parentId: string,
    args: Prisma.TablaExtraidaFindManyArgs
  ): Promise<PrismaTablaExtraida[]> {
    return this.prisma.archivoPdf
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .tablaExtraidas(args);
  }
}
