/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsInt,
  Min,
  Max,
} from "class-validator";
import { ProcesoUpdateManyWithoutArchivoPdfsInput } from "./ProcesoUpdateManyWithoutArchivoPdfsInput";
import { Type } from "class-transformer";
import { ResultadoOcrUpdateManyWithoutArchivoPdfsInput } from "./ResultadoOcrUpdateManyWithoutArchivoPdfsInput";
import { TablaExtraidaUpdateManyWithoutArchivoPdfsInput } from "./TablaExtraidaUpdateManyWithoutArchivoPdfsInput";

@InputType()
class ArchivoPdfUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  formato?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombreArchivo?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProcesoUpdateManyWithoutArchivoPdfsInput,
  })
  @ValidateNested()
  @Type(() => ProcesoUpdateManyWithoutArchivoPdfsInput)
  @IsOptional()
  @Field(() => ProcesoUpdateManyWithoutArchivoPdfsInput, {
    nullable: true,
  })
  procesos?: ProcesoUpdateManyWithoutArchivoPdfsInput;

  @ApiProperty({
    required: false,
    type: () => ResultadoOcrUpdateManyWithoutArchivoPdfsInput,
  })
  @ValidateNested()
  @Type(() => ResultadoOcrUpdateManyWithoutArchivoPdfsInput)
  @IsOptional()
  @Field(() => ResultadoOcrUpdateManyWithoutArchivoPdfsInput, {
    nullable: true,
  })
  resultadoOcrs?: ResultadoOcrUpdateManyWithoutArchivoPdfsInput;

  @ApiProperty({
    required: false,
    type: () => TablaExtraidaUpdateManyWithoutArchivoPdfsInput,
  })
  @ValidateNested()
  @Type(() => TablaExtraidaUpdateManyWithoutArchivoPdfsInput)
  @IsOptional()
  @Field(() => TablaExtraidaUpdateManyWithoutArchivoPdfsInput, {
    nullable: true,
  })
  tablaExtraidas?: TablaExtraidaUpdateManyWithoutArchivoPdfsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  tamano?: number | null;
}

export { ArchivoPdfUpdateInput as ArchivoPdfUpdateInput };
