/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { ProcesoListRelationFilter } from "../../proceso/base/ProcesoListRelationFilter";
import { ResultadoOcrListRelationFilter } from "../../resultadoOcr/base/ResultadoOcrListRelationFilter";
import { TablaExtraidaListRelationFilter } from "../../tablaExtraida/base/TablaExtraidaListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

@InputType()
class ArchivoPdfWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  formato?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nombreArchivo?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ProcesoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProcesoListRelationFilter)
  @IsOptional()
  @Field(() => ProcesoListRelationFilter, {
    nullable: true,
  })
  procesos?: ProcesoListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ResultadoOcrListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ResultadoOcrListRelationFilter)
  @IsOptional()
  @Field(() => ResultadoOcrListRelationFilter, {
    nullable: true,
  })
  resultadoOcrs?: ResultadoOcrListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TablaExtraidaListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TablaExtraidaListRelationFilter)
  @IsOptional()
  @Field(() => TablaExtraidaListRelationFilter, {
    nullable: true,
  })
  tablaExtraidas?: TablaExtraidaListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  tamano?: IntNullableFilter;
}

export { ArchivoPdfWhereInput as ArchivoPdfWhereInput };
