/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ArchivoPdfService } from "../archivoPdf.service";
import { ArchivoPdfCreateInput } from "./ArchivoPdfCreateInput";
import { ArchivoPdf } from "./ArchivoPdf";
import { ArchivoPdfFindManyArgs } from "./ArchivoPdfFindManyArgs";
import { ArchivoPdfWhereUniqueInput } from "./ArchivoPdfWhereUniqueInput";
import { ArchivoPdfUpdateInput } from "./ArchivoPdfUpdateInput";
import { ProcesoFindManyArgs } from "../../proceso/base/ProcesoFindManyArgs";
import { Proceso } from "../../proceso/base/Proceso";
import { ProcesoWhereUniqueInput } from "../../proceso/base/ProcesoWhereUniqueInput";
import { ResultadoOcrFindManyArgs } from "../../resultadoOcr/base/ResultadoOcrFindManyArgs";
import { ResultadoOcr } from "../../resultadoOcr/base/ResultadoOcr";
import { ResultadoOcrWhereUniqueInput } from "../../resultadoOcr/base/ResultadoOcrWhereUniqueInput";
import { TablaExtraidaFindManyArgs } from "../../tablaExtraida/base/TablaExtraidaFindManyArgs";
import { TablaExtraida } from "../../tablaExtraida/base/TablaExtraida";
import { TablaExtraidaWhereUniqueInput } from "../../tablaExtraida/base/TablaExtraidaWhereUniqueInput";

export class ArchivoPdfControllerBase {
  constructor(protected readonly service: ArchivoPdfService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ArchivoPdf })
  async createArchivoPdf(
    @common.Body() data: ArchivoPdfCreateInput
  ): Promise<ArchivoPdf> {
    return await this.service.createArchivoPdf({
      data: data,
      select: {
        createdAt: true,
        formato: true,
        id: true,
        nombreArchivo: true,
        tamano: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ArchivoPdf] })
  @ApiNestedQuery(ArchivoPdfFindManyArgs)
  async archivoPdfs(@common.Req() request: Request): Promise<ArchivoPdf[]> {
    const args = plainToClass(ArchivoPdfFindManyArgs, request.query);
    return this.service.archivoPdfs({
      ...args,
      select: {
        createdAt: true,
        formato: true,
        id: true,
        nombreArchivo: true,
        tamano: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ArchivoPdf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async archivoPdf(
    @common.Param() params: ArchivoPdfWhereUniqueInput
  ): Promise<ArchivoPdf | null> {
    const result = await this.service.archivoPdf({
      where: params,
      select: {
        createdAt: true,
        formato: true,
        id: true,
        nombreArchivo: true,
        tamano: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ArchivoPdf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateArchivoPdf(
    @common.Param() params: ArchivoPdfWhereUniqueInput,
    @common.Body() data: ArchivoPdfUpdateInput
  ): Promise<ArchivoPdf | null> {
    try {
      return await this.service.updateArchivoPdf({
        where: params,
        data: data,
        select: {
          createdAt: true,
          formato: true,
          id: true,
          nombreArchivo: true,
          tamano: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ArchivoPdf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteArchivoPdf(
    @common.Param() params: ArchivoPdfWhereUniqueInput
  ): Promise<ArchivoPdf | null> {
    try {
      return await this.service.deleteArchivoPdf({
        where: params,
        select: {
          createdAt: true,
          formato: true,
          id: true,
          nombreArchivo: true,
          tamano: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/procesos")
  @ApiNestedQuery(ProcesoFindManyArgs)
  async findProcesos(
    @common.Req() request: Request,
    @common.Param() params: ArchivoPdfWhereUniqueInput
  ): Promise<Proceso[]> {
    const query = plainToClass(ProcesoFindManyArgs, request.query);
    const results = await this.service.findProcesos(params.id, {
      ...query,
      select: {
        archivoPdf: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        estado: true,
        id: true,
        mensajeError: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/procesos")
  async connectProcesos(
    @common.Param() params: ArchivoPdfWhereUniqueInput,
    @common.Body() body: ProcesoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      procesos: {
        connect: body,
      },
    };
    await this.service.updateArchivoPdf({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/procesos")
  async updateProcesos(
    @common.Param() params: ArchivoPdfWhereUniqueInput,
    @common.Body() body: ProcesoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      procesos: {
        set: body,
      },
    };
    await this.service.updateArchivoPdf({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/procesos")
  async disconnectProcesos(
    @common.Param() params: ArchivoPdfWhereUniqueInput,
    @common.Body() body: ProcesoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      procesos: {
        disconnect: body,
      },
    };
    await this.service.updateArchivoPdf({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/resultadoOcrs")
  @ApiNestedQuery(ResultadoOcrFindManyArgs)
  async findResultadoOcrs(
    @common.Req() request: Request,
    @common.Param() params: ArchivoPdfWhereUniqueInput
  ): Promise<ResultadoOcr[]> {
    const query = plainToClass(ResultadoOcrFindManyArgs, request.query);
    const results = await this.service.findResultadoOcrs(params.id, {
      ...query,
      select: {
        archivoPdf: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        lenguajeDetectado: true,
        textoExtraido: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/resultadoOcrs")
  async connectResultadoOcrs(
    @common.Param() params: ArchivoPdfWhereUniqueInput,
    @common.Body() body: ResultadoOcrWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      resultadoOcrs: {
        connect: body,
      },
    };
    await this.service.updateArchivoPdf({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/resultadoOcrs")
  async updateResultadoOcrs(
    @common.Param() params: ArchivoPdfWhereUniqueInput,
    @common.Body() body: ResultadoOcrWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      resultadoOcrs: {
        set: body,
      },
    };
    await this.service.updateArchivoPdf({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/resultadoOcrs")
  async disconnectResultadoOcrs(
    @common.Param() params: ArchivoPdfWhereUniqueInput,
    @common.Body() body: ResultadoOcrWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      resultadoOcrs: {
        disconnect: body,
      },
    };
    await this.service.updateArchivoPdf({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/tablaExtraidas")
  @ApiNestedQuery(TablaExtraidaFindManyArgs)
  async findTablaExtraidas(
    @common.Req() request: Request,
    @common.Param() params: ArchivoPdfWhereUniqueInput
  ): Promise<TablaExtraida[]> {
    const query = plainToClass(TablaExtraidaFindManyArgs, request.query);
    const results = await this.service.findTablaExtraidas(params.id, {
      ...query,
      select: {
        archivoPdf: {
          select: {
            id: true,
          },
        },

        contenidoTabla: true,
        createdAt: true,
        id: true,
        numeroColumnas: true,
        numeroFilas: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tablaExtraidas")
  async connectTablaExtraidas(
    @common.Param() params: ArchivoPdfWhereUniqueInput,
    @common.Body() body: TablaExtraidaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tablaExtraidas: {
        connect: body,
      },
    };
    await this.service.updateArchivoPdf({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tablaExtraidas")
  async updateTablaExtraidas(
    @common.Param() params: ArchivoPdfWhereUniqueInput,
    @common.Body() body: TablaExtraidaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tablaExtraidas: {
        set: body,
      },
    };
    await this.service.updateArchivoPdf({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tablaExtraidas")
  async disconnectTablaExtraidas(
    @common.Param() params: ArchivoPdfWhereUniqueInput,
    @common.Body() body: TablaExtraidaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tablaExtraidas: {
        disconnect: body,
      },
    };
    await this.service.updateArchivoPdf({
      where: params,
      data,
      select: { id: true },
    });
  }
}
