/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsInt,
  Min,
  Max,
} from "class-validator";
import { ProcesoCreateNestedManyWithoutArchivoPdfsInput } from "./ProcesoCreateNestedManyWithoutArchivoPdfsInput";
import { Type } from "class-transformer";
import { ResultadoOcrCreateNestedManyWithoutArchivoPdfsInput } from "./ResultadoOcrCreateNestedManyWithoutArchivoPdfsInput";
import { TablaExtraidaCreateNestedManyWithoutArchivoPdfsInput } from "./TablaExtraidaCreateNestedManyWithoutArchivoPdfsInput";

@InputType()
class ArchivoPdfCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  formato?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombreArchivo?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProcesoCreateNestedManyWithoutArchivoPdfsInput,
  })
  @ValidateNested()
  @Type(() => ProcesoCreateNestedManyWithoutArchivoPdfsInput)
  @IsOptional()
  @Field(() => ProcesoCreateNestedManyWithoutArchivoPdfsInput, {
    nullable: true,
  })
  procesos?: ProcesoCreateNestedManyWithoutArchivoPdfsInput;

  @ApiProperty({
    required: false,
    type: () => ResultadoOcrCreateNestedManyWithoutArchivoPdfsInput,
  })
  @ValidateNested()
  @Type(() => ResultadoOcrCreateNestedManyWithoutArchivoPdfsInput)
  @IsOptional()
  @Field(() => ResultadoOcrCreateNestedManyWithoutArchivoPdfsInput, {
    nullable: true,
  })
  resultadoOcrs?: ResultadoOcrCreateNestedManyWithoutArchivoPdfsInput;

  @ApiProperty({
    required: false,
    type: () => TablaExtraidaCreateNestedManyWithoutArchivoPdfsInput,
  })
  @ValidateNested()
  @Type(() => TablaExtraidaCreateNestedManyWithoutArchivoPdfsInput)
  @IsOptional()
  @Field(() => TablaExtraidaCreateNestedManyWithoutArchivoPdfsInput, {
    nullable: true,
  })
  tablaExtraidas?: TablaExtraidaCreateNestedManyWithoutArchivoPdfsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  tamano?: number | null;
}

export { ArchivoPdfCreateInput as ArchivoPdfCreateInput };
