/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TablaExtraida } from "./TablaExtraida";
import { TablaExtraidaCountArgs } from "./TablaExtraidaCountArgs";
import { TablaExtraidaFindManyArgs } from "./TablaExtraidaFindManyArgs";
import { TablaExtraidaFindUniqueArgs } from "./TablaExtraidaFindUniqueArgs";
import { CreateTablaExtraidaArgs } from "./CreateTablaExtraidaArgs";
import { UpdateTablaExtraidaArgs } from "./UpdateTablaExtraidaArgs";
import { DeleteTablaExtraidaArgs } from "./DeleteTablaExtraidaArgs";
import { ArchivoPdf } from "../../archivoPdf/base/ArchivoPdf";
import { TablaExtraidaService } from "../tablaExtraida.service";
@graphql.Resolver(() => TablaExtraida)
export class TablaExtraidaResolverBase {
  constructor(protected readonly service: TablaExtraidaService) {}

  async _tablaExtraidasMeta(
    @graphql.Args() args: TablaExtraidaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TablaExtraida])
  async tablaExtraidas(
    @graphql.Args() args: TablaExtraidaFindManyArgs
  ): Promise<TablaExtraida[]> {
    return this.service.tablaExtraidas(args);
  }

  @graphql.Query(() => TablaExtraida, { nullable: true })
  async tablaExtraida(
    @graphql.Args() args: TablaExtraidaFindUniqueArgs
  ): Promise<TablaExtraida | null> {
    const result = await this.service.tablaExtraida(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TablaExtraida)
  async createTablaExtraida(
    @graphql.Args() args: CreateTablaExtraidaArgs
  ): Promise<TablaExtraida> {
    return await this.service.createTablaExtraida({
      ...args,
      data: {
        ...args.data,

        archivoPdf: args.data.archivoPdf
          ? {
              connect: args.data.archivoPdf,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => TablaExtraida)
  async updateTablaExtraida(
    @graphql.Args() args: UpdateTablaExtraidaArgs
  ): Promise<TablaExtraida | null> {
    try {
      return await this.service.updateTablaExtraida({
        ...args,
        data: {
          ...args.data,

          archivoPdf: args.data.archivoPdf
            ? {
                connect: args.data.archivoPdf,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TablaExtraida)
  async deleteTablaExtraida(
    @graphql.Args() args: DeleteTablaExtraidaArgs
  ): Promise<TablaExtraida | null> {
    try {
      return await this.service.deleteTablaExtraida(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => ArchivoPdf, {
    nullable: true,
    name: "archivoPdf",
  })
  async getArchivoPdf(
    @graphql.Parent() parent: TablaExtraida
  ): Promise<ArchivoPdf | null> {
    const result = await this.service.getArchivoPdf(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
