/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TablaExtraidaService } from "../tablaExtraida.service";
import { TablaExtraidaCreateInput } from "./TablaExtraidaCreateInput";
import { TablaExtraida } from "./TablaExtraida";
import { TablaExtraidaFindManyArgs } from "./TablaExtraidaFindManyArgs";
import { TablaExtraidaWhereUniqueInput } from "./TablaExtraidaWhereUniqueInput";
import { TablaExtraidaUpdateInput } from "./TablaExtraidaUpdateInput";

export class TablaExtraidaControllerBase {
  constructor(protected readonly service: TablaExtraidaService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TablaExtraida })
  async createTablaExtraida(
    @common.Body() data: TablaExtraidaCreateInput
  ): Promise<TablaExtraida> {
    return await this.service.createTablaExtraida({
      data: {
        ...data,

        archivoPdf: data.archivoPdf
          ? {
              connect: data.archivoPdf,
            }
          : undefined,
      },
      select: {
        archivoPdf: {
          select: {
            id: true,
          },
        },

        contenidoTabla: true,
        createdAt: true,
        id: true,
        numeroColumnas: true,
        numeroFilas: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TablaExtraida] })
  @ApiNestedQuery(TablaExtraidaFindManyArgs)
  async tablaExtraidas(
    @common.Req() request: Request
  ): Promise<TablaExtraida[]> {
    const args = plainToClass(TablaExtraidaFindManyArgs, request.query);
    return this.service.tablaExtraidas({
      ...args,
      select: {
        archivoPdf: {
          select: {
            id: true,
          },
        },

        contenidoTabla: true,
        createdAt: true,
        id: true,
        numeroColumnas: true,
        numeroFilas: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TablaExtraida })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async tablaExtraida(
    @common.Param() params: TablaExtraidaWhereUniqueInput
  ): Promise<TablaExtraida | null> {
    const result = await this.service.tablaExtraida({
      where: params,
      select: {
        archivoPdf: {
          select: {
            id: true,
          },
        },

        contenidoTabla: true,
        createdAt: true,
        id: true,
        numeroColumnas: true,
        numeroFilas: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TablaExtraida })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTablaExtraida(
    @common.Param() params: TablaExtraidaWhereUniqueInput,
    @common.Body() data: TablaExtraidaUpdateInput
  ): Promise<TablaExtraida | null> {
    try {
      return await this.service.updateTablaExtraida({
        where: params,
        data: {
          ...data,

          archivoPdf: data.archivoPdf
            ? {
                connect: data.archivoPdf,
              }
            : undefined,
        },
        select: {
          archivoPdf: {
            select: {
              id: true,
            },
          },

          contenidoTabla: true,
          createdAt: true,
          id: true,
          numeroColumnas: true,
          numeroFilas: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TablaExtraida })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTablaExtraida(
    @common.Param() params: TablaExtraidaWhereUniqueInput
  ): Promise<TablaExtraida | null> {
    try {
      return await this.service.deleteTablaExtraida({
        where: params,
        select: {
          archivoPdf: {
            select: {
              id: true,
            },
          },

          contenidoTabla: true,
          createdAt: true,
          id: true,
          numeroColumnas: true,
          numeroFilas: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
