/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  TablaExtraida as PrismaTablaExtraida,
  ArchivoPdf as PrismaArchivoPdf,
} from "@prisma/client";

export class TablaExtraidaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TablaExtraidaCountArgs, "select">
  ): Promise<number> {
    return this.prisma.tablaExtraida.count(args);
  }

  async tablaExtraidas(
    args: Prisma.TablaExtraidaFindManyArgs
  ): Promise<PrismaTablaExtraida[]> {
    return this.prisma.tablaExtraida.findMany(args);
  }
  async tablaExtraida(
    args: Prisma.TablaExtraidaFindUniqueArgs
  ): Promise<PrismaTablaExtraida | null> {
    return this.prisma.tablaExtraida.findUnique(args);
  }
  async createTablaExtraida(
    args: Prisma.TablaExtraidaCreateArgs
  ): Promise<PrismaTablaExtraida> {
    return this.prisma.tablaExtraida.create(args);
  }
  async updateTablaExtraida(
    args: Prisma.TablaExtraidaUpdateArgs
  ): Promise<PrismaTablaExtraida> {
    return this.prisma.tablaExtraida.update(args);
  }
  async deleteTablaExtraida(
    args: Prisma.TablaExtraidaDeleteArgs
  ): Promise<PrismaTablaExtraida> {
    return this.prisma.tablaExtraida.delete(args);
  }

  async getArchivoPdf(parentId: string): Promise<PrismaArchivoPdf | null> {
    return this.prisma.tablaExtraida
      .findUnique({
        where: { id: parentId },
      })
      .archivoPdf();
  }
}
